ui: tape
browsers:
    - name: chrome
      version: [36, -2..latest]
    - name: safari
      version: -2..latest
    - name: firefox
      version: -2..latest
    - name: ie
      version: 9..latest
    - name: opera
      version: -1..latest
    - name: android
      version: -2..latest
browserify:
   - transform: coffeeify
   - options:
       extensions:
         - .coffee
