// eslint-disable-next-line jest/no-export
module.exports = [
  {
    password: '1q2w3e4r5t',
    result: {
      password: '1q2w3e4r5t',
      guesses: 291,
      guessesLog10: 2.4638929889859074,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 9,
          token: '1q2w3e4r5t',
          matchedWord: '1q2w3e4r5t',
          rank: 290,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: false,
          baseGuesses: 290,
          uppercaseVariations: 1,
          l33tVariations: 1,
          guesses: 290,
          guessesLog10: 2.4623979978989556,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 10476,
        onlineThrottling10PerSecond: 29.1,
        offlineSlowHashing1e4PerSecond: 0.0291,
        offlineFastHashing1e10PerSecond: 2.91e-8,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '3 hours',
        onlineThrottling10PerSecond: '29 seconds',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is a commonly used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: '1Q2w3e4r5t',
    result: {
      password: '1Q2w3e4r5t',
      guesses: 581,
      guessesLog10: 2.76417613239033,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 9,
          token: '1Q2w3e4r5t',
          matchedWord: '1q2w3e4r5t',
          rank: 290,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: false,
          baseGuesses: 290,
          uppercaseVariations: 2,
          l33tVariations: 1,
          guesses: 580,
          guessesLog10: 2.763427993562937,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 20916,
        onlineThrottling10PerSecond: 58.1,
        offlineSlowHashing1e4PerSecond: 0.0581,
        offlineFastHashing1e10PerSecond: 5.81e-8,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '6 hours',
        onlineThrottling10PerSecond: '58 seconds',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is a commonly used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: '1q2w3e4r5T',
    result: {
      password: '1q2w3e4r5T',
      guesses: 581,
      guessesLog10: 2.76417613239033,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 9,
          token: '1q2w3e4r5T',
          matchedWord: '1q2w3e4r5t',
          rank: 290,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: false,
          baseGuesses: 290,
          uppercaseVariations: 2,
          l33tVariations: 1,
          guesses: 580,
          guessesLog10: 2.763427993562937,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 20916,
        onlineThrottling10PerSecond: 58.1,
        offlineSlowHashing1e4PerSecond: 0.0581,
        offlineFastHashing1e10PerSecond: 5.81e-8,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '6 hours',
        onlineThrottling10PerSecond: '58 seconds',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is a commonly used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: 'abcdefg123',
    result: {
      password: 'abcdefg123',
      guesses: 15000,
      guessesLog10: 4.176091259055681,
      sequence: [
        {
          pattern: 'sequence',
          i: 0,
          j: 6,
          token: 'abcdefg',
          sequenceName: 'lower',
          sequenceSpace: 26,
          ascending: true,
          guesses: 50,
          guessesLog10: 1.6989700043360185,
        },
        {
          pattern: 'sequence',
          i: 7,
          j: 9,
          token: '123',
          sequenceName: 'digits',
          sequenceSpace: 10,
          ascending: true,
          guesses: 50,
          guessesLog10: 1.6989700043360185,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 540000,
        onlineThrottling10PerSecond: 1500,
        offlineSlowHashing1e4PerSecond: 1.5,
        offlineFastHashing1e10PerSecond: 0.0000015,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '6 days',
        onlineThrottling10PerSecond: '25 minutes',
        offlineSlowHashing1e4PerSecond: '2 seconds',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'Common character sequences like "abc" are easy to guess.',
        suggestions: [
          'Add more words that are less common.',
          'Avoid common character sequences.',
        ],
      },
    },
  },
  {
    password: 'TESTERINO',
    result: {
      password: 'TESTERINO',
      guesses: 1910000,
      guessesLog10: 6.281033367247726,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 5,
          token: 'TESTER',
          matchedWord: 'tester',
          rank: 475,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: false,
          baseGuesses: 475,
          uppercaseVariations: 2,
          l33tVariations: 1,
          guesses: 950,
          guessesLog10: 2.9777236052888476,
        },
        {
          pattern: 'bruteforce',
          token: 'INO',
          i: 6,
          j: 8,
          guesses: 1000,
          guessesLog10: 2.9999999999999996,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 68760000,
        onlineThrottling10PerSecond: 191000,
        offlineSlowHashing1e4PerSecond: 191,
        offlineFastHashing1e10PerSecond: 0.000191,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '2 years',
        onlineThrottling10PerSecond: '2 days',
        offlineSlowHashing1e4PerSecond: '3 minutes',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 2,
      feedback: {
        warning: 'This is similar to a commonly used password.',
        suggestions: [
          'Add more words that are less common.',
          'Capitalize some, but not all letters.',
        ],
      },
    },
  },
  {
    password: 'aaaaaaa',
    result: {
      password: 'aaaaaaa',
      guesses: 290874,
      guessesLog10: 5.46370490322997,
      sequence: [
        {
          pattern: 'bruteforce',
          token: 'a',
          i: 0,
          j: 0,
          guesses: 11,
          guessesLog10: 1.041392685158225,
        },
        {
          pattern: 'dictionary',
          i: 1,
          j: 6,
          token: 'aaaaaa',
          matchedWord: 'aaaaaa',
          rank: 12767,
          dictionaryName: 'us_tv_and_film',
          reversed: false,
          l33t: false,
          baseGuesses: 12767,
          uppercaseVariations: 1,
          l33tVariations: 1,
          guesses: 12767,
          guessesLog10: 4.106088858382442,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 10471464,
        onlineThrottling10PerSecond: 29087.4,
        offlineSlowHashing1e4PerSecond: 29.0874,
        offlineFastHashing1e10PerSecond: 0.0000290874,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '4 months',
        onlineThrottling10PerSecond: '8 hours',
        offlineSlowHashing1e4PerSecond: '29 seconds',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: '',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: 'Daniel',
    result: {
      password: 'Daniel',
      guesses: 25,
      guessesLog10: 1.3979400086720375,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 5,
          token: 'Daniel',
          matchedWord: 'daniel',
          rank: 12,
          dictionaryName: 'maleNames',
          reversed: false,
          l33t: false,
          baseGuesses: 12,
          uppercaseVariations: 2,
          l33tVariations: 1,
          guesses: 24,
          guessesLog10: 1.380211241711606,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 900,
        onlineThrottling10PerSecond: 2.5,
        offlineSlowHashing1e4PerSecond: 0.0025,
        offlineFastHashing1e10PerSecond: 2.5e-9,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '15 minutes',
        onlineThrottling10PerSecond: '3 seconds',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'Single names or surnames are easy to guess.',
        suggestions: [
          'Add more words that are less common.',
          'Capitalize more than the first letter.',
        ],
      },
    },
  },
  {
    password: '1234qwer',
    result: {
      password: '1234qwer',
      guesses: 87,
      guessesLog10: 1.9395192526186182,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 7,
          token: '1234qwer',
          matchedWord: '1234qwer',
          rank: 86,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: false,
          baseGuesses: 86,
          uppercaseVariations: 1,
          l33tVariations: 1,
          guesses: 86,
          guessesLog10: 1.9344984512435675,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 3132,
        onlineThrottling10PerSecond: 8.7,
        offlineSlowHashing1e4PerSecond: 0.0087,
        offlineFastHashing1e10PerSecond: 8.7e-9,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '52 minutes',
        onlineThrottling10PerSecond: '9 seconds',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is a frequently used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: '1234qwe',
    result: {
      password: '1234qwe',
      guesses: 2017,
      guessesLog10: 3.304705898212765,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 6,
          token: '1234qwe',
          matchedWord: '1234qwe',
          rank: 2016,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: false,
          baseGuesses: 2016,
          uppercaseVariations: 1,
          l33tVariations: 1,
          guesses: 2016,
          guessesLog10: 3.3044905277734875,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 72612,
        onlineThrottling10PerSecond: 201.7,
        offlineSlowHashing1e4PerSecond: 0.2017,
        offlineFastHashing1e10PerSecond: 2.017e-7,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '20 hours',
        onlineThrottling10PerSecond: '3 minutes',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'This is a commonly used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: '1234qwert',
    result: {
      password: '1234qwert',
      guesses: 11892,
      guessesLog10: 4.0752549005329,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 7,
          token: '1234qwer',
          matchedWord: '1234qwer',
          rank: 86,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: false,
          baseGuesses: 86,
          uppercaseVariations: 1,
          l33tVariations: 1,
          guesses: 86,
          guessesLog10: 1.9344984512435675,
        },
        {
          pattern: 'bruteforce',
          token: 't',
          i: 8,
          j: 8,
          guesses: 11,
          guessesLog10: 1.041392685158225,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 428112,
        onlineThrottling10PerSecond: 1189.2,
        offlineSlowHashing1e4PerSecond: 1.1892,
        offlineFastHashing1e10PerSecond: 0.0000011892,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '5 days',
        onlineThrottling10PerSecond: '20 minutes',
        offlineSlowHashing1e4PerSecond: '1 second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'This is similar to a commonly used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: 'password',
    result: {
      password: 'password',
      guesses: 3,
      guessesLog10: 0.4771212547196623,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 7,
          token: 'password',
          matchedWord: 'password',
          rank: 2,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: false,
          baseGuesses: 2,
          uppercaseVariations: 1,
          l33tVariations: 1,
          guesses: 2,
          guessesLog10: 0.30102999566398114,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 108,
        onlineThrottling10PerSecond: 0.3,
        offlineSlowHashing1e4PerSecond: 0.0003,
        offlineFastHashing1e10PerSecond: 3e-10,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '2 minutes',
        onlineThrottling10PerSecond: 'less than a second',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is a heavily used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: '2010abc',
    result: {
      password: '2010abc',
      guesses: 15000,
      guessesLog10: 4.176091259055681,
      sequence: [
        {
          pattern: 'regex',
          token: '2010',
          i: 0,
          j: 3,
          regexName: 'recentYear',
          regexMatch: ['2010'],
          guesses: 50,
          guessesLog10: 1.6989700043360185,
        },
        {
          pattern: 'sequence',
          i: 4,
          j: 6,
          token: 'abc',
          sequenceName: 'lower',
          sequenceSpace: 26,
          ascending: true,
          guesses: 50,
          guessesLog10: 1.6989700043360185,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 540000,
        onlineThrottling10PerSecond: 1500,
        offlineSlowHashing1e4PerSecond: 1.5,
        offlineFastHashing1e10PerSecond: 0.0000015,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '6 days',
        onlineThrottling10PerSecond: '25 minutes',
        offlineSlowHashing1e4PerSecond: '2 seconds',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'Recent years are easy to guess.',
        suggestions: [
          'Add more words that are less common.',
          'Avoid recent years.',
          'Avoid years that are associated with you.',
        ],
      },
    },
  },
  {
    password: 'abcabcabcabc',
    result: {
      password: 'abcabcabcabc',
      guesses: 15100000000,
      guessesLog10: 10.178976947293169,
      sequence: [
        {
          pattern: 'bruteforce',
          token: 'abcabc',
          i: 0,
          j: 5,
          guesses: 1000000,
          guessesLog10: 5.999999999999999,
        },
        {
          pattern: 'sequence',
          i: 6,
          j: 8,
          token: 'abc',
          sequenceName: 'lower',
          sequenceSpace: 26,
          ascending: true,
          guesses: 50,
          guessesLog10: 1.6989700043360185,
        },
        {
          pattern: 'sequence',
          i: 9,
          j: 11,
          token: 'abc',
          sequenceName: 'lower',
          sequenceSpace: 26,
          ascending: true,
          guesses: 50,
          guessesLog10: 1.6989700043360185,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 543600000000,
        onlineThrottling10PerSecond: 1510000000,
        offlineSlowHashing1e4PerSecond: 1510000,
        offlineFastHashing1e10PerSecond: 1.51,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: 'centuries',
        onlineThrottling10PerSecond: '47 years',
        offlineSlowHashing1e4PerSecond: '17 days',
        offlineFastHashing1e10PerSecond: '2 seconds',
      },
      score: 4,
      feedback: { warning: '', suggestions: [] },
    },
  },
  {
    password: 'qwer',
    result: {
      password: 'qwer',
      guesses: 1693,
      guessesLog10: 3.228656958108935,
      sequence: [
        {
          pattern: 'spatial',
          i: 0,
          j: 3,
          token: 'qwer',
          graph: 'qwerty',
          turns: 1,
          shiftedCount: 0,
          guesses: 1692,
          guessesLog10: 3.2284003587030043,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 60948,
        onlineThrottling10PerSecond: 169.3,
        offlineSlowHashing1e4PerSecond: 0.1693,
        offlineFastHashing1e10PerSecond: 1.693e-7,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '17 hours',
        onlineThrottling10PerSecond: '3 minutes',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'Straight rows of keys are easy to guess.',
        suggestions: [
          'Add more words that are less common.',
          'Use longer keyboard patterns and change typing direction multiple times.',
        ],
      },
    },
  },
  {
    password: 'P4$$w0rd',
    result: {
      password: 'P4$$w0rd',
      guesses: 33,
      guessesLog10: 1.5185139398778873,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 7,
          token: 'P4$$w0rd',
          matchedWord: 'password',
          rank: 2,
          dictionaryName: 'passwords',
          reversed: false,
          l33t: true,
          sub: { 0: 'o', 4: 'a', $: 's' },
          subDisplay: '0 -> o, 4 -> a, $ -> s',
          baseGuesses: 2,
          uppercaseVariations: 2,
          l33tVariations: 8,
          guesses: 32,
          guessesLog10: 1.5051499783199058,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 1188,
        onlineThrottling10PerSecond: 3.3,
        offlineSlowHashing1e4PerSecond: 0.0033,
        offlineFastHashing1e10PerSecond: 3.3e-9,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '20 minutes',
        onlineThrottling10PerSecond: '3 seconds',
        offlineSlowHashing1e4PerSecond: 'less than a second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is similar to a commonly used password.',
        suggestions: [
          'Add more words that are less common.',
          'Capitalize more than the first letter.',
          "Avoid predictable letter substitutions like '@' for 'a'.",
        ],
      },
    },
  },
  {
    password: 'aA!1',
    result: {
      password: 'aA!1',
      guesses: 10001,
      guessesLog10: 4.000043427276863,
      sequence: [
        {
          pattern: 'bruteforce',
          token: 'aA!1',
          i: 0,
          j: 3,
          guesses: 10000,
          guessesLog10: 4,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 360036,
        onlineThrottling10PerSecond: 1000.1,
        offlineSlowHashing1e4PerSecond: 1.0001,
        offlineFastHashing1e10PerSecond: 0.0000010001,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: '4 days',
        onlineThrottling10PerSecond: '17 minutes',
        offlineSlowHashing1e4PerSecond: '1 second',
        offlineFastHashing1e10PerSecond: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: '',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: 'dgo9dsghasdoghi8/!&IT/§(ihsdhf8o7o',
    result: {
      password: 'dgo9dsghasdoghi8/!&IT/§(ihsdhf8o7o',
      guesses: 2.34e33,
      guessesLog10: 33.36921585741014,
      sequence: [
        {
          pattern: 'bruteforce',
          token: 'dgo9dsg',
          i: 0,
          j: 6,
          guesses: 10000000,
          guessesLog10: 7,
        },
        {
          pattern: 'dictionary',
          i: 7,
          j: 9,
          token: 'has',
          matchedWord: 'has',
          rank: 24,
          dictionaryName: 'english_wikipedia',
          reversed: false,
          l33t: false,
          baseGuesses: 24,
          uppercaseVariations: 1,
          l33tVariations: 1,
          guesses: 50,
          guessesLog10: 1.6989700043360185,
        },
        {
          pattern: 'dictionary',
          i: 10,
          j: 11,
          token: 'do',
          matchedWord: 'do',
          rank: 17,
          dictionaryName: 'us_tv_and_film',
          reversed: false,
          l33t: false,
          baseGuesses: 17,
          uppercaseVariations: 1,
          l33tVariations: 1,
          guesses: 50,
          guessesLog10: 1.6989700043360185,
        },
        {
          pattern: 'sequence',
          i: 12,
          j: 14,
          token: 'ghi',
          sequenceName: 'lower',
          sequenceSpace: 26,
          ascending: true,
          guesses: 78,
          guessesLog10: 1.8920946026904801,
        },
        {
          pattern: 'bruteforce',
          token: '8/!&IT/§(ihsdhf8o7o',
          i: 15,
          j: 33,
          guesses: 10000000000000000000,
          guessesLog10: 19,
        },
      ],
      crackTimesSeconds: {
        onlineThrottling100PerHour: 8.424e34,
        onlineThrottling10PerSecond: 2.34e32,
        offlineSlowHashing1e4PerSecond: 2.34e29,
        offlineFastHashing1e10PerSecond: 2.34e23,
      },
      crackTimesDisplay: {
        onlineThrottling100PerHour: 'centuries',
        onlineThrottling10PerSecond: 'centuries',
        offlineSlowHashing1e4PerSecond: 'centuries',
        offlineFastHashing1e10PerSecond: 'centuries',
      },
      score: 4,
      feedback: { warning: '', suggestions: [] },
    },
  },
]
