// eslint-disable-next-line jest/no-export
module.exports = [
  {
    password: 'abcdefg123',
    result: {
      password: 'abcdefg123',
      guesses: 15000,
      guesses_log10: 4.176091259055681,
      sequence: [
        {
          pattern: 'sequence',
          i: 0,
          j: 6,
          token: 'abcdefg',
          sequence_name: 'lower',
          sequence_space: 26,
          ascending: true,
          guesses: 50,
          guesses_log10: 1.6989700043360185,
        },
        {
          pattern: 'sequence',
          i: 7,
          j: 9,
          token: '123',
          sequence_name: 'digits',
          sequence_space: 10,
          ascending: true,
          guesses: 50,
          guesses_log10: 1.6989700043360185,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 540000,
        online_no_throttling_10_per_second: 1500,
        offline_slow_hashing_1e4_per_second: 1.5,
        offline_fast_hashing_1e10_per_second: 0.0000015,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '6 days',
        online_no_throttling_10_per_second: '25 minutes',
        offline_slow_hashing_1e4_per_second: '2 seconds',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'Common character sequences like "abc" are easy to guess.',
        suggestions: [
          'Add more words that are less common.',
          'Avoid common character sequences.',
        ],
      },
    },
  },
  {
    password: 'TESTERINO',
    result: {
      password: 'TESTERINO',
      guesses: 1910000,
      guesses_log10: 6.281033367247726,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 5,
          token: 'TESTER',
          matched_word: 'tester',
          rank: 475,
          dictionary_name: 'passwords',
          reversed: false,
          l33t: false,
          base_guesses: 475,
          uppercase_variations: 2,
          l33t_variations: 1,
          guesses: 950,
          guesses_log10: 2.9777236052888476,
        },
        {
          pattern: 'bruteforce',
          token: 'INO',
          i: 6,
          j: 8,
          guesses: 1000,
          guesses_log10: 2.9999999999999996,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 68760000,
        online_no_throttling_10_per_second: 191000,
        offline_slow_hashing_1e4_per_second: 191,
        offline_fast_hashing_1e10_per_second: 0.000191,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '2 years',
        online_no_throttling_10_per_second: '2 days',
        offline_slow_hashing_1e4_per_second: '3 minutes',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 2,
      feedback: {
        warning: 'This is similar to a commonly used password.',
        suggestions: [
          'Add more words that are less common.',
          'Capitalize some, but not all letters.',
        ],
      },
    },
  },
  {
    password: 'aaaaaaa',
    result: {
      password: 'aaaaaaa',
      guesses: 290874,
      guesses_log10: 5.46370490322997,
      sequence: [
        {
          pattern: 'bruteforce',
          token: 'a',
          i: 0,
          j: 0,
          guesses: 11,
          guesses_log10: 1.041392685158225,
        },
        {
          pattern: 'dictionary',
          i: 1,
          j: 6,
          token: 'aaaaaa',
          matched_word: 'aaaaaa',
          rank: 12767,
          dictionary_name: 'us_tv_and_film',
          reversed: false,
          l33t: false,
          base_guesses: 12767,
          uppercase_variations: 1,
          l33t_variations: 1,
          guesses: 12767,
          guesses_log10: 4.106088858382442,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 10471464,
        online_no_throttling_10_per_second: 29087.4,
        offline_slow_hashing_1e4_per_second: 29.0874,
        offline_fast_hashing_1e10_per_second: 0.0000290874,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '4 months',
        online_no_throttling_10_per_second: '8 hours',
        offline_slow_hashing_1e4_per_second: '29 seconds',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: '',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: 'Daniel',
    result: {
      password: 'Daniel',
      guesses: 25,
      guesses_log10: 1.3979400086720375,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 5,
          token: 'Daniel',
          matched_word: 'daniel',
          rank: 12,
          dictionary_name: 'male_names',
          reversed: false,
          l33t: false,
          base_guesses: 12,
          uppercase_variations: 2,
          l33t_variations: 1,
          guesses: 24,
          guesses_log10: 1.380211241711606,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 900,
        online_no_throttling_10_per_second: 2.5,
        offline_slow_hashing_1e4_per_second: 0.0025,
        offline_fast_hashing_1e10_per_second: 2.5e-9,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '15 minutes',
        online_no_throttling_10_per_second: '3 seconds',
        offline_slow_hashing_1e4_per_second: 'less than a second',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'Single names or surnames are easy to guess.',
        suggestions: [
          'Add more words that are less common.',
          'Capitalize more than the first letter.',
        ],
      },
    },
  },
  {
    password: '1234qwer',
    result: {
      password: '1234qwer',
      guesses: 87,
      guesses_log10: 1.9395192526186182,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 7,
          token: '1234qwer',
          matched_word: '1234qwer',
          rank: 86,
          dictionary_name: 'passwords',
          reversed: false,
          l33t: false,
          base_guesses: 86,
          uppercase_variations: 1,
          l33t_variations: 1,
          guesses: 86,
          guesses_log10: 1.9344984512435675,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 3132,
        online_no_throttling_10_per_second: 8.7,
        offline_slow_hashing_1e4_per_second: 0.0087,
        offline_fast_hashing_1e10_per_second: 8.7e-9,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '52 minutes',
        online_no_throttling_10_per_second: '9 seconds',
        offline_slow_hashing_1e4_per_second: 'less than a second',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is a frequently used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: '1234qwe',
    result: {
      password: '1234qwe',
      guesses: 2017,
      guesses_log10: 3.304705898212765,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 6,
          token: '1234qwe',
          matched_word: '1234qwe',
          rank: 2016,
          dictionary_name: 'passwords',
          reversed: false,
          l33t: false,
          base_guesses: 2016,
          uppercase_variations: 1,
          l33t_variations: 1,
          guesses: 2016,
          guesses_log10: 3.3044905277734875,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 72612,
        online_no_throttling_10_per_second: 201.7,
        offline_slow_hashing_1e4_per_second: 0.2017,
        offline_fast_hashing_1e10_per_second: 2.017e-7,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '20 hours',
        online_no_throttling_10_per_second: '3 minutes',
        offline_slow_hashing_1e4_per_second: 'less than a second',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'This is a commonly used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: '1234qwert',
    result: {
      password: '1234qwert',
      guesses: 11892,
      guesses_log10: 4.0752549005329,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 7,
          token: '1234qwer',
          matched_word: '1234qwer',
          rank: 86,
          dictionary_name: 'passwords',
          reversed: false,
          l33t: false,
          base_guesses: 86,
          uppercase_variations: 1,
          l33t_variations: 1,
          guesses: 86,
          guesses_log10: 1.9344984512435675,
        },
        {
          pattern: 'bruteforce',
          token: 't',
          i: 8,
          j: 8,
          guesses: 11,
          guesses_log10: 1.041392685158225,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 428112,
        online_no_throttling_10_per_second: 1189.2,
        offline_slow_hashing_1e4_per_second: 1.1892,
        offline_fast_hashing_1e10_per_second: 0.0000011892,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '5 days',
        online_no_throttling_10_per_second: '20 minutes',
        offline_slow_hashing_1e4_per_second: '1 second',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'This is similar to a commonly used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: 'password',
    result: {
      password: 'password',
      guesses: 3,
      guesses_log10: 0.4771212547196623,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 7,
          token: 'password',
          matched_word: 'password',
          rank: 2,
          dictionary_name: 'passwords',
          reversed: false,
          l33t: false,
          base_guesses: 2,
          uppercase_variations: 1,
          l33t_variations: 1,
          guesses: 2,
          guesses_log10: 0.30102999566398114,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 108,
        online_no_throttling_10_per_second: 0.3,
        offline_slow_hashing_1e4_per_second: 0.0003,
        offline_fast_hashing_1e10_per_second: 3e-10,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '2 minutes',
        online_no_throttling_10_per_second: 'less than a second',
        offline_slow_hashing_1e4_per_second: 'less than a second',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is a heavily used password.',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: '2010abc',
    result: {
      password: '2010abc',
      guesses: 15000,
      guesses_log10: 4.176091259055681,
      sequence: [
        {
          pattern: 'regex',
          token: '2010',
          i: 0,
          j: 3,
          regex_name: 'recent_year',
          regex_match: ['2010'],
          guesses: 50,
          guesses_log10: 1.6989700043360185,
        },
        {
          pattern: 'sequence',
          i: 4,
          j: 6,
          token: 'abc',
          sequence_name: 'lower',
          sequence_space: 26,
          ascending: true,
          guesses: 50,
          guesses_log10: 1.6989700043360185,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 540000,
        online_no_throttling_10_per_second: 1500,
        offline_slow_hashing_1e4_per_second: 1.5,
        offline_fast_hashing_1e10_per_second: 0.0000015,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '6 days',
        online_no_throttling_10_per_second: '25 minutes',
        offline_slow_hashing_1e4_per_second: '2 seconds',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'Recent years are easy to guess.',
        suggestions: [
          'Add more words that are less common.',
          'Avoid recent years.',
          'Avoid years that are associated with you.',
        ],
      },
    },
  },
  {
    password: 'abcabcabcabc',
    result: {
      password: 'abcabcabcabc',
      guesses: 15100000000,
      guesses_log10: 10.178976947293169,
      sequence: [
        {
          pattern: 'bruteforce',
          token: 'abcabc',
          i: 0,
          j: 5,
          guesses: 1000000,
          guesses_log10: 5.999999999999999,
        },
        {
          pattern: 'sequence',
          i: 6,
          j: 8,
          token: 'abc',
          sequence_name: 'lower',
          sequence_space: 26,
          ascending: true,
          guesses: 50,
          guesses_log10: 1.6989700043360185,
        },
        {
          pattern: 'sequence',
          i: 9,
          j: 11,
          token: 'abc',
          sequence_name: 'lower',
          sequence_space: 26,
          ascending: true,
          guesses: 50,
          guesses_log10: 1.6989700043360185,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 543600000000,
        online_no_throttling_10_per_second: 1510000000,
        offline_slow_hashing_1e4_per_second: 1510000,
        offline_fast_hashing_1e10_per_second: 1.51,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: 'centuries',
        online_no_throttling_10_per_second: '47 years',
        offline_slow_hashing_1e4_per_second: '17 days',
        offline_fast_hashing_1e10_per_second: '2 seconds',
      },
      score: 4,
      feedback: { warning: '', suggestions: [] },
    },
  },
  {
    password: 'qwer',
    result: {
      password: 'qwer',
      guesses: 1693,
      guesses_log10: 3.228656958108935,
      sequence: [
        {
          pattern: 'spatial',
          i: 0,
          j: 3,
          token: 'qwer',
          graph: 'qwerty',
          turns: 1,
          shifted_count: 0,
          guesses: 1692,
          guesses_log10: 3.2284003587030043,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 60948,
        online_no_throttling_10_per_second: 169.3,
        offline_slow_hashing_1e4_per_second: 0.1693,
        offline_fast_hashing_1e10_per_second: 1.693e-7,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '17 hours',
        online_no_throttling_10_per_second: '3 minutes',
        offline_slow_hashing_1e4_per_second: 'less than a second',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: 'Straight rows of keys are easy to guess.',
        suggestions: [
          'Add more words that are less common.',
          'Use longer keyboard patterns and change typing direction multiple times.',
        ],
      },
    },
  },
  {
    password: 'P4$$w0rd',
    result: {
      password: 'P4$$w0rd',
      guesses: 33,
      guesses_log10: 1.5185139398778873,
      sequence: [
        {
          pattern: 'dictionary',
          i: 0,
          j: 7,
          token: 'P4$$w0rd',
          matched_word: 'password',
          rank: 2,
          dictionary_name: 'passwords',
          reversed: false,
          l33t: true,
          sub: { 0: 'o', 4: 'a', $: 's' },
          sub_display: '0 -> o, 4 -> a, $ -> s',
          base_guesses: 2,
          uppercase_variations: 2,
          l33t_variations: 8,
          guesses: 32,
          guesses_log10: 1.5051499783199058,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 1188,
        online_no_throttling_10_per_second: 3.3,
        offline_slow_hashing_1e4_per_second: 0.0033,
        offline_fast_hashing_1e10_per_second: 3.3e-9,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '20 minutes',
        online_no_throttling_10_per_second: '3 seconds',
        offline_slow_hashing_1e4_per_second: 'less than a second',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 0,
      feedback: {
        warning: 'This is similar to a commonly used password.',
        suggestions: [
          'Add more words that are less common.',
          'Capitalize more than the first letter.',
          "Avoid predictable letter substitutions like '@' for 'a'.",
        ],
      },
    },
  },
  {
    password: 'aA!1',
    result: {
      password: 'aA!1',
      guesses: 10001,
      guesses_log10: 4.000043427276863,
      sequence: [
        {
          pattern: 'bruteforce',
          token: 'aA!1',
          i: 0,
          j: 3,
          guesses: 10000,
          guesses_log10: 4,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 360036,
        online_no_throttling_10_per_second: 1000.1,
        offline_slow_hashing_1e4_per_second: 1.0001,
        offline_fast_hashing_1e10_per_second: 0.0000010001,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: '4 days',
        online_no_throttling_10_per_second: '17 minutes',
        offline_slow_hashing_1e4_per_second: '1 second',
        offline_fast_hashing_1e10_per_second: 'less than a second',
      },
      score: 1,
      feedback: {
        warning: '',
        suggestions: ['Add more words that are less common.'],
      },
    },
  },
  {
    password: 'dgo9dsghasdoghi8/!&IT/§(ihsdhf8o7o',
    result: {
      password: 'dgo9dsghasdoghi8/!&IT/§(ihsdhf8o7o',
      guesses: 2.34e33,
      guesses_log10: 33.36921585741014,
      sequence: [
        {
          pattern: 'bruteforce',
          token: 'dgo9dsg',
          i: 0,
          j: 6,
          guesses: 10000000,
          guesses_log10: 7,
        },
        {
          pattern: 'dictionary',
          i: 7,
          j: 9,
          token: 'has',
          matched_word: 'has',
          rank: 24,
          dictionary_name: 'english_wikipedia',
          reversed: false,
          l33t: false,
          base_guesses: 24,
          uppercase_variations: 1,
          l33t_variations: 1,
          guesses: 50,
          guesses_log10: 1.6989700043360185,
        },
        {
          pattern: 'dictionary',
          i: 10,
          j: 11,
          token: 'do',
          matched_word: 'do',
          rank: 17,
          dictionary_name: 'us_tv_and_film',
          reversed: false,
          l33t: false,
          base_guesses: 17,
          uppercase_variations: 1,
          l33t_variations: 1,
          guesses: 50,
          guesses_log10: 1.6989700043360185,
        },
        {
          pattern: 'sequence',
          i: 12,
          j: 14,
          token: 'ghi',
          sequence_name: 'lower',
          sequence_space: 26,
          ascending: true,
          guesses: 78,
          guesses_log10: 1.8920946026904801,
        },
        {
          pattern: 'bruteforce',
          token: '8/!&IT/§(ihsdhf8o7o',
          i: 15,
          j: 33,
          guesses: 10000000000000000000,
          guesses_log10: 19,
        },
      ],
      crackTimesSeconds: {
        online_throttling_100_per_hour: 8.424e34,
        online_no_throttling_10_per_second: 2.34e32,
        offline_slow_hashing_1e4_per_second: 2.34e29,
        offline_fast_hashing_1e10_per_second: 2.34e23,
      },
      crackTimesDisplay: {
        online_throttling_100_per_hour: 'centuries',
        online_no_throttling_10_per_second: 'centuries',
        offline_slow_hashing_1e4_per_second: 'centuries',
        offline_fast_hashing_1e10_per_second: 'centuries',
      },
      score: 4,
      feedback: { warning: '', suggestions: [] },
    },
  },
]
